produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }
presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }
panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }
livraison:
    path:     /panier/livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }
validation:
    path:     /panier/validation
    defaults: { _controller: EcommerceBundle:Panier:validation }
# categorie
categories:
    path:     /categorie
    defaults: { _controller: EcommerceBundle:Categories:menu }
categorie:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:categories }