produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

categorie:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:categories }

rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }
