<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategories($categorie)
    {
       return $this->createQueryBuilder('produits')
            ->select('produits')
            ->where('produits.categorie = :categorie')
            ->orderBy('produits.id')
            ->setParameter('categorie',$categorie)
            ->getQuery()
            ->getResult();
    }
}
