<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategories($categorie)
    {
       return $this->createQueryBuilder('produits')
            ->select('produits')
            ->where('produits.categorie = :categorie')
            ->andWhere('produits.disponible = 1')
            ->orderBy('produits.id')
            ->setParameter('categorie',$categorie)
            ->getQuery()
            ->getResult();
    }

    public function recherche($chaine){
        return $this->createQueryBuilder('u')
            ->select('u')
            // pour recherche il faut utiliser en like pas en égale
            ->where('u.nom like :chaine')
            // vérification si le produit est disponible ou pas
            ->andWhere('u.disponible = 1')
            ->orderBy('u.id')
            ->setParameter('chaine',$chaine)
            ->getQuery()
            ->getResult()
            ;
    }
    public function findArray($array){
        return $this->createQueryBuilder('u')
            ->select('u')
            // pour verifieR si un élement est dans une tableaux
            ->where('u.id in (:array)')
            ->setParameter('array',$array)
            ->getQuery()
            ->getResult()
            ;
    }
}
